import { defineConfig } from 'vite'
import laravel from 'laravel-vite-plugin'

export default defineConfig({
  plugins: [
    laravel({
      input: [
        // CSS
        'resources/css/app.css',
        'resources/css/welcome.css',
        'resources/css/about.css',
        'resources/css/contact.css',
        'resources/css/login.css',
        'resources/css/daftarakun.css',
        'resources/css/navbar.css',
        'resources/css/footer.css',
        'resources/css/global.css',
        'resources/css/admin.css',
        'resources/css/admin-dashboard.css',
        'resources/css/admin-customer.css',
        'resources/css/admin-driver.css',
        'resources/css/admin-mobil.css',
        'resources/css/admin-pengajuan.css',
        'resources/css/admin-pengiriman.css',
        'resources/css/admin-riwayat.css',
        'resources/css/admin-saw.css',
        'resources/css/admin-users.css',
        'resources/css/bukti-pengiriman.css',
        'resources/css/chat-admin.css',
        'resources/css/chat-driver.css',
        'resources/css/chat-superadmin.css',
        'resources/css/driver.css',
        'resources/css/superadmin.css',
        // JS
        'resources/js/app.js',
        'resources/js/welcome.js',
        'resources/js/about.js',
        'resources/js/contact.js',
        'resources/js/login.js',
        'resources/js/daftarakun.js',
        'resources/js/navbar.js',
        'resources/js/footer.js',
        'resources/js/admin.js',
        'resources/js/admin-dashboard.js',
        'resources/js/admin-customer.js',
        'resources/js/admin-driver.js',
        'resources/js/admin-mobil.js',
        'resources/js/admin-pengajuan.js',
        'resources/js/admin-pengiriman.js',
        'resources/js/admin-riwayat.js',
        'resources/js/admin-saw.js',
        'resources/js/admin-users.js',
        'resources/js/bukti-pengiriman.js',
        'resources/js/chat-admin.js',
        'resources/js/chat-driver.js',
        'resources/js/chat-superadmin.js',
        'resources/js/driver.js',
        'resources/js/superadmin.js',
      ],
      refresh: true,
    }),
  ],
})
